"""empty message

Revision ID: 42017ef40505
Revises: 56c6d126e6c6
Create Date: 2024-06-21 04:37:07.642780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42017ef40505'
down_revision = '56c6d126e6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # Drop existing temporary table if it exists
    op.drop_table('_alembic_tmp_user')
    
    # Recreate _alembic_tmp_user table with img column nullable and default value
    op.create_table('_alembic_tmp_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=12), nullable=False),
        sa.Column('email', sa.String(length=25), nullable=False),
        sa.Column('password', sa.String(length=60), nullable=False),
        sa.Column('img', sa.String(length=20), nullable=False, server_default='static/images/default.jpg'),  # Provide a default value
        sa.PrimaryKeyConstraint('id')
    )
    
    # Alter user table img column to be NOT NULL if needed
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('img',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=False,
                              server_default='static/images/default.jpg')
    
    # Migrate data from user table to _alembic_tmp_user, ensuring default for img where NULL
    op.execute(
        """
        INSERT INTO _alembic_tmp_user (id, username, email, password, img)
        SELECT id, username, email, password, COALESCE(img, 'static/images/default.jpg') FROM user
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temporary table and revert user table img column to nullable
    op.drop_table('_alembic_tmp_user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

   
    # ### end Alembic commands ###
